// One-off generator for the Spice Island Boerewors logo mark + icon/OG assets.
// Run from the project root:  node scripts/gen-logo.mjs
// Produces: lib/logoMark.ts (geometry for the React <Logo/>), app/icon.svg,
// app/apple-icon.png, app/favicon.ico, public/logo-mark.svg,
// public/logo-square-512.png, public/og-image.png
import { writeFileSync } from "node:fs";
import sharp from "sharp";

const C = 50; // centre of the 100x100 mark space
const round = (n) => Math.round(n * 100) / 100;
const pt = (r, deg) => {
  const a = (deg * Math.PI) / 180;
  return [round(C + r * Math.cos(a)), round(C - r * Math.sin(a))]; // y flipped (CCW visual)
};

// --- Archimedean spiral: ~3 coils, opening to a tied end at top-right (~35deg) ---
const R0 = 4;
const TURNS = 3;
const THETA_END = TURNS * 2 * Math.PI + (35 * Math.PI) / 180; // end at 35deg
const R_END = 43;
const K = (R_END - R0) / THETA_END;
let d = "";
for (let i = 0; ; i++) {
  const th = i * 0.12;
  if (th > THETA_END) break;
  const r = R0 + K * th;
  const x = round(C + r * Math.cos(th));
  const y = round(C - r * Math.sin(th));
  d += (i === 0 ? "M" : "L") + x + "," + y + " ";
}
const SPIRAL_D = d.trim();
const [ex, ey] = pt(R_END, 35); // outer end point

// --- tied casing knot at the outer end ---
const knotC = pt(R_END + 6, 33);
const KNOT_D =
  `M${ex},${ey} Q${round(ex + 4)},${round(ey - 9)} ${knotC[0]},${knotC[1]} ` +
  `Q${round(knotC[0] + 7)},${round(knotC[1] + 3)} ${round(knotC[0] + 2)},${round(knotC[1] + 7)} ` +
  `Q${round(knotC[0] - 4)},${round(knotC[1] + 4)} ${round(ex + 3)},${round(ey + 1)}`;

// --- a couple of short "motion" wisps just outside the lower-left of the coil ---
const wisp = (r, a1, a2) => {
  let s = "";
  const steps = 6;
  for (let i = 0; i <= steps; i++) {
    const [x, y] = pt(r, a1 + ((a2 - a1) * i) / steps);
    s += (i === 0 ? "M" : "L") + x + "," + y + " ";
  }
  return s.trim();
};
const SKETCH_DS = [wisp(47, 206, 238), wisp(50.5, 210, 233)];

// --- three spice dots, lower-right outside the coil ---
const DOTS = [
  { cx: pt(49, -42)[0], cy: pt(49, -42)[1], r: 1.7 },
  { cx: pt(53, -49)[0], cy: pt(53, -49)[1], r: 1.4 },
  { cx: pt(48, -55)[0], cy: pt(48, -55)[1], r: 1.2 },
];

// ---------- lib/logoMark.ts (consumed by components/Logo.tsx) ----------
const ts = `// AUTO-GENERATED by scripts/gen-logo.mjs — do not edit by hand.
export const MARK_VIEWBOX = "0 0 100 100";
export const SPIRAL_D = ${JSON.stringify(SPIRAL_D)};
export const KNOT_D = ${JSON.stringify(KNOT_D)};
export const SKETCH_DS: string[] = ${JSON.stringify(SKETCH_DS)};
export const DOTS: { cx: number; cy: number; r: number }[] = ${JSON.stringify(DOTS)};
`;
writeFileSync("lib/logoMark.ts", ts);

// ---------- shared SVG fragment for the mark ----------
function markGroup({ color, sw }) {
  const strokes =
    `<path d="${SPIRAL_D}" fill="none" stroke="${color}" stroke-width="${sw}" stroke-linecap="round" stroke-linejoin="round"/>` +
    `<path d="${KNOT_D}" fill="none" stroke="${color}" stroke-width="${sw}" stroke-linecap="round" stroke-linejoin="round"/>` +
    SKETCH_DS.map(
      (p) =>
        `<path d="${p}" fill="none" stroke="${color}" stroke-width="${round(
          sw * 0.8
        )}" stroke-linecap="round" stroke-linejoin="round"/>`
    ).join("") +
    DOTS.map((dt) => `<circle cx="${dt.cx}" cy="${dt.cy}" r="${dt.r}" fill="${color}"/>`).join("");
  return strokes;
}

// ---------- public/logo-mark.svg (charcoal mark, transparent) ----------
writeFileSync(
  "public/logo-mark.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" role="img" aria-label="Spice Island Boerewors">${markGroup(
    { color: "#1c1a19", sw: 3.2 }
  )}</svg>\n`
);

// ---------- app/icon.svg (charcoal tile, cream mark) ----------
const tileSvg = (size) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 64 64">` +
  `<rect width="64" height="64" rx="13" fill="#1c1a19"/>` +
  `<g transform="translate(9,9) scale(0.46)"><g>` +
  markGroup({ color: "#faf7f2", sw: 4.2 }) +
  `</g></g></svg>`;
writeFileSync("app/icon.svg", tileSvg(64) + "\n");

// ---------- logo-square (cream tile, charcoal mark) for JSON-LD logo ----------
const squareSvg =
  `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">` +
  `<rect width="512" height="512" rx="96" fill="#faf7f2"/>` +
  `<g transform="translate(106,86) scale(3.0)">` +
  markGroup({ color: "#1c1a19", sw: 3.2 }) +
  `</g></svg>`;

// ---------- OG image (1200x630, cream bg, mark + wordmark) ----------
const ogSvg =
  `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">` +
  `<rect width="1200" height="630" fill="#faf7f2"/>` +
  `<rect x="0" y="0" width="1200" height="10" fill="#cca23b"/>` +
  `<g transform="translate(515,70) scale(1.7)">` +
  markGroup({ color: "#1c1a19", sw: 3.2 }) +
  `</g>` +
  `<text x="600" y="430" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="78" font-weight="600" letter-spacing="14" fill="#1c1a19">SPICE ISLAND</text>` +
  `<text x="600" y="492" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="34" letter-spacing="20" fill="#9e2a15">B O E R E W O R S</text>` +
  `<text x="600" y="560" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="26" letter-spacing="2" fill="#6b6258">Handcrafted South African sausages &#183; Zanzibar</text>` +
  `</svg>`;

// ---------- rasterize ----------
const svgBuf = (s) => Buffer.from(s);
await sharp(svgBuf(tileSvg(180))).png().resize(180, 180).toFile("app/apple-icon.png");
await sharp(svgBuf(squareSvg)).png().toFile("public/logo-square-512.png");
await sharp(svgBuf(ogSvg)).png().toFile("public/og-image.png");

// favicon.ico (PNG-in-ICO, 48 + 32)
function ico(entries) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(entries.length, 4);
  let offset = 6 + entries.length * 16;
  const dir = [];
  for (const e of entries) {
    const d = Buffer.alloc(16);
    d.writeUInt8(e.size >= 256 ? 0 : e.size, 0);
    d.writeUInt8(e.size >= 256 ? 0 : e.size, 1);
    d.writeUInt16LE(1, 4);
    d.writeUInt16LE(32, 6);
    d.writeUInt32LE(e.buf.length, 8);
    d.writeUInt32LE(offset, 12);
    dir.push(d);
    offset += e.buf.length;
  }
  return Buffer.concat([header, ...dir, ...entries.map((e) => e.buf)]);
}
const p48 = await sharp(svgBuf(tileSvg(48))).png().resize(48, 48).toBuffer();
const p32 = await sharp(svgBuf(tileSvg(32))).png().resize(32, 32).toBuffer();
writeFileSync("app/favicon.ico", ico([{ size: 48, buf: p48 }, { size: 32, buf: p32 }]));

console.log("Logo assets generated.");
